---
title: "FE & Baseline"
output:
  html_document:
    df_print: paged
    css: styles.css
---

```{r setup, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

load_reqs <- function(reqs) {
  for(pkg in reqs) {
    if (!(pkg %in% installed.packages())) { install.packages(pkg) }
    suppressPackageStartupMessages(library(pkg, character.only = T))
  }
}

# ADD LIBRARIES HERE
load_reqs(c("tidyr", "dplyr", "data.table", "purrr", "ggplot2", "corrplot", "gridExtra", "grid", "cowplot", "PerformanceAnalytics", "dichromat", "wesanderson"))
```

```{r echo=FALSE, warning=FALSE}
########################################
### Loading Data
########################################

train <- read.csv('../data/house_price_train.csv')
test <- read.csv('../data/house_price_test.csv')
```


### Drop variables
```{r echo=TRUE, warning=FALSE}
for (i in c("sqft_lot", "sqft_lot15", "date", "yr_built", "long", "lat",            "sqft_above")){
  train[[i]] <- NULL
  test[[i]] <- NULL
}
```

***

### binarize
```{r echo=TRUE, warning=FALSE}
train$yr_renovated[train$yr_renovated != 0] = 1
train$sqft_basement[train$sqft_basement != 0] = 1

test$yr_renovated[test$yr_renovated != 0] = 1
test$sqft_basement[test$sqft_basement != 0] = 1

```

***

### Convert to factor
```{r echo=TRUE, warning=FALSE}
for (i in c('bedrooms', 'floors', 'waterfront', 'view', 'condition', 'zipcode', 'yr_renovated', 'sqft_basement')){
  train[[i]] = as.factor(train[[i]])
  test[[i]] = as.factor(test[[i]])
}

train <- train[train$bedrooms != 11, ]
train <- train[train$bedrooms != 33, ]
train <- train[train$sqft_living != 13540, ]
```

### Log Price
```{r echo=TRUE, warning=FALSE}
train$logPrice <- log(train$price)
```


```{r echo=FALSE, warning=FALSE}
########################################
### SAVE prepared data
########################################
saveRDS(train, "../data/train_prepared.rds")
saveRDS(test, "../data/test_prepared.rds")
```

### Baseline Model

```{r echo=TRUE, warning=FALSE}
model <- lm(formula = logPrice ~ bedrooms + bathrooms + sqft_living
                        + floors + waterfront + view + condition
                        + grade + sqft_basement + yr_renovated + zipcode
                        + sqft_living15,
                  data = train)

summary(model)
```

**R2 score of 87.7**

***

```{r echo=FALSE, warning=FALSE}
y_pred = predict(model, newdata = train)
y_pred_reversed  = exp(y_pred)

ggplot() +
  geom_point(aes(x = train$sqft_living, y = train$price),
             colour = 'black') +
  geom_line(aes(x = train$sqft_living, y = y_pred_reversed),
            colour = 'blue') +
  ggtitle('Predictions on Train') +
  xlab('Sqft_living') +
  ylab('Price')
```

***

### Residuals Analysis

```{r}
hist(model$residuals)
plot(model)
paste("Risudals Mean: ", mean(model$residuals), sep=" ")
```

***

### MAPE

```{r echo=FALSE, warning=FALSE}
Metrics::mape(train$price, y_pred_reversed)
```

**High MAPE**